### ISSUE TITLE
Does this watcher support Django?

### ISSUE THREAD

**Issue by hsluoyz** [ScienceLogic/flask-casbin-redis-watcher#3]
If yes, how to use it in Django?

I saw the README is for Flask. Can you provide an example Django? Thanks!

**Comment by hsluoyz** [comment]
@dfresh613

**Comment by dfresh613** [comment]
This module is pretty simple, theres no reason that it wouldn't work with django I think.

However, I haven't deployed with Django myself, and so have no examples to provide.

**Comment by hsluoyz** [comment]
Thanks!
